// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Belt_Array = require("rescript/lib/js/belt_Array.js");

var input = Fs.readFileSync("input/Week2/Year2020Day4.sample.txt", "utf8");

function splitPassport(data) {
  return data.split("\n\n");
}

function splitField(data) {
  return data.split(/\s/);
}

function parsePassport(param) {
  
}

console.log(Belt_Array.map(input.split("\n\n"), splitField));

exports.input = input;
exports.splitPassport = splitPassport;
exports.splitField = splitField;
exports.parsePassport = parsePassport;
/* input Not a pure module */
