// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Belt_Array = require("rescript/lib/js/belt_Array.js");

var input = Fs.readFileSync("input/Week1/Year2020Day5.input.txt", "utf8");

function splitInput(pattern) {
  return pattern.split("\n");
}

var inputArray = Belt_Array.map(input.split("\n"), (function (x) {
        return x.split("");
      }));

console.log(inputArray);

function getRowInfo(info) {
  return Belt_Array.slice(info, 0, 7);
}

function getRowNum(rowInfo) {
  return Belt_Array.reduceWithIndex(rowInfo, 0, (function (acc, v, i) {
                var exp = rowInfo.length - i | 0;
                Math.pow(2, exp);
                return acc + v | 0;
              }));
}

exports.input = input;
exports.splitInput = splitInput;
exports.inputArray = inputArray;
exports.getRowInfo = getRowInfo;
exports.getRowNum = getRowNum;
/* input Not a pure module */
