// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Belt_List = require("rescript/lib/js/belt_List.js");
var Belt_Array = require("rescript/lib/js/belt_Array.js");
var Belt_Option = require("rescript/lib/js/belt_Option.js");
var Caml_splice_call = require("rescript/lib/js/caml_splice_call.js");
var Belt_SortArrayInt = require("rescript/lib/js/belt_SortArrayInt.js");

var input = Fs.readFileSync("input/Week1/Year2020Day5.input.txt", "utf8");

function splitNewLine(pattern) {
  return pattern.split("\n");
}

function stringToArray(str) {
  return str.split("");
}

function seatSignToBinary(info) {
  switch (info) {
    case "B" :
    case "R" :
        return 1;
    default:
      return 0;
  }
}

function getSeatId(num) {
  return Belt_Array.reduceWithIndex(num, 0, (function (acc, v, i) {
                var exp = num.length - (i + 1 | 0) | 0;
                var increment = Math.pow(2, exp);
                return acc + Math.imul(v, increment) | 0;
              }));
}

function getMaxId(ids) {
  return Caml_splice_call.spliceApply(Math.max, [ids]);
}

function getMaxId2(ids) {
  return Belt_Option.getWithDefault(Belt_Array.get(Belt_Array.reverse(Belt_SortArrayInt.stableSort(ids)), 0), 0);
}

var seatIds = Belt_Array.map(Belt_Array.map(Belt_Array.map(input.split("\n"), stringToArray), (function (xs) {
            return Belt_Array.map(xs, seatSignToBinary);
          })), getSeatId);

console.log(getMaxId2(seatIds));

function getMinId(ids) {
  return Caml_splice_call.spliceApply(Math.min, [ids]);
}

var maxId = getMaxId2(seatIds);

var minId = Caml_splice_call.spliceApply(Math.min, [seatIds]);

function setSlidingWindow(ids) {
  return Belt_Array.mapWithIndex(ids, (function (i, x) {
                var num = Belt_Array.get(ids, i + 1 | 0);
                if (num !== undefined) {
                  return [
                          x,
                          num
                        ];
                } else {
                  return [
                          x,
                          x + 1 | 0
                        ];
                }
              }));
}

function getEmptySeatIds(idPairs) {
  return Belt_Array.map(idPairs, (function (xs) {
                return Belt_Array.range(xs[0] + 1 | 0, xs[1] - 1 | 0);
              }));
}

function getDiff(idPair) {
  return idPair[1] - idPair[0] | 0;
}

var concatSeatId = Belt_Array.concatMany;

function sortListAscending(data) {
  return Belt_List.sort(data, (function (a, b) {
                return a - b | 0;
              }));
}

function setSlidingWindowList(_ids, _pairList) {
  while(true) {
    var pairList = _pairList;
    var ids = _ids;
    if (!ids) {
      return pairList;
    }
    var otherSeatIds = ids.tl;
    if (!otherSeatIds) {
      return pairList;
    }
    var seatId2 = Belt_List.headExn(otherSeatIds);
    var $$new = Belt_List.concat(pairList, {
          hd: [
            ids.hd,
            seatId2
          ],
          tl: /* [] */0
        });
    _pairList = $$new;
    _ids = otherSeatIds;
    continue ;
  };
}

function keepEmptyPair(idPairs) {
  return Belt_List.keep(idPairs, (function (p) {
                return getDiff(p) !== 1;
              }));
}

function getEmptyId(idPair) {
  return Belt_Array.range(idPair[0] + 1 | 0, idPair[1] - 1 | 0);
}

function getEmptySeatIdsList(idPairs) {
  return Belt_List.map(idPairs, getEmptyId);
}

console.log(Belt_Array.concatMany(Belt_List.toArray(Belt_List.map(keepEmptyPair(setSlidingWindowList(sortListAscending(Belt_List.fromArray(seatIds)), /* [] */0)), getEmptyId))));

exports.input = input;
exports.splitNewLine = splitNewLine;
exports.stringToArray = stringToArray;
exports.seatSignToBinary = seatSignToBinary;
exports.getSeatId = getSeatId;
exports.getMaxId = getMaxId;
exports.getMaxId2 = getMaxId2;
exports.seatIds = seatIds;
exports.getMinId = getMinId;
exports.maxId = maxId;
exports.minId = minId;
exports.setSlidingWindow = setSlidingWindow;
exports.getEmptySeatIds = getEmptySeatIds;
exports.getDiff = getDiff;
exports.concatSeatId = concatSeatId;
exports.sortListAscending = sortListAscending;
exports.setSlidingWindowList = setSlidingWindowList;
exports.keepEmptyPair = keepEmptyPair;
exports.getEmptyId = getEmptyId;
exports.getEmptySeatIdsList = getEmptySeatIdsList;
/* input Not a pure module */
